{{ config(materialized='semantic_view') }}

TABLES (
    CUSTOMERS AS {{ source('epower_gold', 'customer_dim') }}
        PRIMARY KEY (CUSTOMER_KEY),
    BILLING AS {{ source('epower_gold', 'billing_history') }}
        PRIMARY KEY (BILLING_ID) WITH SYNONYMS = ('Rechnungen','invoices')
)

RELATIONSHIPS (
    BILLING_TO_CUSTOMERS AS BILLING(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY)
)

FACTS (
    BILLING.CONSUMPTION AS CONSUMPTION_KWH,
    BILLING.BILLING_AMOUNT AS AMOUNT
)

DIMENSIONS (
    CUSTOMERS.CUSTOMER_KEY AS CUSTOMER_KEY,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMER_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_CUSTOMER_NAME,
    CUSTOMERS.HOUSING_TYPE AS HOUSING_TYPE,
    BILLING.BILLING_ID AS BILLING_ID,
    BILLING.BILLING_DATE AS BILLING_DATE,
    BILLING.BILLING_TYPE AS BILLING_TYPE,
    BILLING.PAYMENT_STATUS AS PAYMENT_STATUS
)

METRICS (
    BILLING.TOTAL_CONSUMPTION AS SUM(BILLING.CONSUMPTION),
    BILLING.AVG_CONSUMPTION AS AVG(BILLING.CONSUMPTION)
)
