{{ config(materialized='semantic_view') }}

TABLES (
    CUSTOMERS AS {{ source('epower_gold', 'customer_dim') }}
        PRIMARY KEY (CUSTOMER_KEY),
    BILLING AS {{ source('epower_gold', 'billing_history') }}
        PRIMARY KEY (BILLING_ID),
    OWNERSHIP AS {{ source('epower_gold', 'customer_products') }}
        PRIMARY KEY (CUSTOMER_PRODUCT_ID),
    DEVICES AS {{ source('epower_bronze', 'epulse_devices') }}
        PRIMARY KEY (CUSTOMER_KEY) WITH SYNONYMS = ('VPP','Virtual Power Plant','Geraete')
)

RELATIONSHIPS (
    BILLING_TO_CUSTOMERS AS BILLING(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY),
    OWNERSHIP_TO_CUSTOMERS AS OWNERSHIP(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY),
    DEVICES_TO_CUSTOMERS AS DEVICES(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY)
)

FACTS (
    BILLING.CONSUMPTION AS CONSUMPTION_KWH,
    BILLING.BILLING_AMOUNT AS AMOUNT
)

DIMENSIONS (
    CUSTOMERS.CUSTOMER_KEY AS CUSTOMER_KEY,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMER_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_CUSTOMER_NAME,
    CUSTOMERS.HOUSING_TYPE AS HOUSING_TYPE,
    BILLING.BILLING_DATE AS BILLING_DATE,
    BILLING.BILLING_TYPE AS BILLING_TYPE,
    OWNERSHIP.CATEGORY_NAME AS CATEGORY_NAME,
    DEVICES.GATEWAY_ID AS GATEWAY_ID,
    DEVICES.HAS_SOLAR AS HAS_SOLAR,
    DEVICES.HAS_BATTERY AS HAS_BATTERY,
    DEVICES.HAS_HEATPUMP AS HAS_HEATPUMP,
    DEVICES.IS_VPP_ENROLLED AS IS_VPP_ENROLLED,
    DEVICES.ENROLLMENT_DATE AS ENROLLMENT_DATE
)

METRICS (
    BILLING.AVG_CONSUMPTION AS AVG(BILLING.CONSUMPTION)
)
