{{ config(materialized='semantic_view') }}

TABLES (
    CUSTOMERS AS {{ source('epower_gold', 'customer_dim') }}
        PRIMARY KEY (CUSTOMER_KEY) WITH SYNONYMS = ('Kunden','customers'),
    PRODUCTS AS {{ source('epower_gold', 'product_dim') }}
        PRIMARY KEY (PRODUCT_KEY) WITH SYNONYMS = ('Produkte','products'),
    REGIONS AS {{ source('epower_gold', 'region_dim') }}
        PRIMARY KEY (REGION_KEY) WITH SYNONYMS = ('Regionen','regions'),
    CONTRACTS AS {{ source('epower_gold', 'sales_fact') }}
        PRIMARY KEY (SALE_ID) WITH SYNONYMS = ('Vertraege','contracts'),
    SALES_REPS AS {{ source('epower_gold', 'sales_rep_dim') }}
        PRIMARY KEY (SALES_REP_KEY) WITH SYNONYMS = ('Berater','consultants'),
    VENDORS AS {{ source('epower_gold', 'vendor_dim') }}
        PRIMARY KEY (VENDOR_KEY) WITH SYNONYMS = ('Lieferanten','vendors','partners')
)

RELATIONSHIPS (
    CONTRACTS_TO_CUSTOMERS AS CONTRACTS(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY),
    CONTRACTS_TO_PRODUCTS AS CONTRACTS(PRODUCT_KEY) REFERENCES PRODUCTS(PRODUCT_KEY),
    CONTRACTS_TO_REGIONS AS CONTRACTS(REGION_KEY) REFERENCES REGIONS(REGION_KEY),
    CONTRACTS_TO_REPS AS CONTRACTS(SALES_REP_KEY) REFERENCES SALES_REPS(SALES_REP_KEY),
    CONTRACTS_TO_VENDORS AS CONTRACTS(VENDOR_KEY) REFERENCES VENDORS(VENDOR_KEY)
)

FACTS (
    CONTRACTS.CONTRACT_AMOUNT AS AMOUNT,
    CONTRACTS.CONTRACT_UNITS AS UNITS,
    PRODUCTS.CAPEX_EUR AS CAPEX_EUR,
    PRODUCTS.OPEX_EUR_YEAR AS OPEX_EUR_YEAR
)

DIMENSIONS (
    CUSTOMERS.CUSTOMER_KEY AS CUSTOMER_KEY,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMER_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_CUSTOMER_NAME,
    CUSTOMERS.CUSTOMER_TYPE AS CUSTOMER_TYPE,
    CUSTOMERS.CITY AS CITY WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_CITY,
    PRODUCTS.PRODUCT_KEY AS PRODUCT_KEY,
    PRODUCTS.PRODUCT_NAME AS PRODUCT_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_PRODUCT_NAME,
    PRODUCTS.CATEGORY_NAME AS CATEGORY_NAME,
    REGIONS.REGION_KEY AS REGION_KEY,
    REGIONS.REGION_NAME AS REGION_NAME,
    CONTRACTS.SALE_ID AS SALE_ID,
    CONTRACTS.CONTRACT_DATE AS DATE,
    SALES_REPS.REP_NAME AS REP_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_REP_NAME,
    VENDORS.VENDOR_NAME AS VENDOR_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_VENDOR_NAME
)

METRICS (
    CONTRACTS.TOTAL_REVENUE AS SUM(CONTRACTS.CONTRACT_AMOUNT),
    CONTRACTS.TOTAL_CONTRACTS AS COUNT(CONTRACTS.SALE_ID),
    CONTRACTS.AVG_CONTRACT_VALUE AS AVG(CONTRACTS.CONTRACT_AMOUNT),
    PRODUCTS.AVG_CAPEX AS AVG(PRODUCTS.CAPEX_EUR),
    PRODUCTS.AVG_OPEX AS AVG(PRODUCTS.OPEX_EUR_YEAR)
)
