{{ config(materialized='semantic_view') }}

TABLES (
    DEPARTMENTS AS {{ source('epower_gold', 'department_dim') }}
        PRIMARY KEY (DEPARTMENT_KEY),
    EMPLOYEES AS {{ source('epower_gold', 'employee_dim') }}
        PRIMARY KEY (EMPLOYEE_KEY),
    HR_RECORDS AS {{ source('epower_gold', 'hr_employee_fact') }}
        PRIMARY KEY (HR_FACT_ID),
    JOBS AS {{ source('epower_gold', 'job_dim') }}
        PRIMARY KEY (JOB_KEY)
)

RELATIONSHIPS (
    HR_TO_DEPARTMENTS AS HR_RECORDS(DEPARTMENT_KEY) REFERENCES DEPARTMENTS(DEPARTMENT_KEY),
    HR_TO_EMPLOYEES AS HR_RECORDS(EMPLOYEE_KEY) REFERENCES EMPLOYEES(EMPLOYEE_KEY),
    HR_TO_JOBS AS HR_RECORDS(JOB_KEY) REFERENCES JOBS(JOB_KEY)
)

FACTS (
    HR_RECORDS.ATTRITION_FLAG AS ATTRITION_FLAG,
    HR_RECORDS.EMPLOYEE_SALARY AS SALARY
)

DIMENSIONS (
    DEPARTMENTS.DEPARTMENT_NAME AS DEPARTMENT_NAME,
    EMPLOYEES.EMPLOYEE_NAME AS EMPLOYEE_NAME,
    EMPLOYEES.GENDER AS GENDER,
    JOBS.JOB_TITLE AS JOB_TITLE
)

METRICS (
    HR_RECORDS.TOTAL_SALARY AS SUM(HR_RECORDS.EMPLOYEE_SALARY),
    HR_RECORDS.AVG_SALARY AS AVG(HR_RECORDS.EMPLOYEE_SALARY)
)
