{{ config(materialized='semantic_view') }}

TABLES (
    CUSTOMERS AS {{ source('epower_gold', 'customer_dim') }}
        PRIMARY KEY (CUSTOMER_KEY),
    TICKETS AS {{ source('epower_gold', 'service_logs') }}
        PRIMARY KEY (LOG_ID) WITH SYNONYMS = ('Tickets','Anfragen')
)

RELATIONSHIPS (
    TICKETS_TO_CUSTOMERS AS TICKETS(CUSTOMER_KEY) REFERENCES CUSTOMERS(CUSTOMER_KEY)
)

DIMENSIONS (
    CUSTOMERS.CUSTOMER_KEY AS CUSTOMER_KEY,
    CUSTOMERS.CUSTOMER_NAME AS CUSTOMER_NAME WITH CORTEX SEARCH SERVICE EPOWER_DEMO.EPOWER_GOLD._CA_CUSTOMER_NAME,
    TICKETS.LOG_ID AS LOG_ID,
    TICKETS.LOG_DATE AS LOG_DATE,
    TICKETS.TOPIC AS TOPIC,
    TICKETS.CATEGORY AS CATEGORY,
    TICKETS.SENTIMENT AS SENTIMENT,
    TICKETS.PRIORITY AS PRIORITY
)

METRICS (
    TICKETS.TOTAL_TICKETS AS COUNT(TICKETS.LOG_ID)
)
